default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/prelaunchr_development.postgresql
  host: localhost
  
test:
  <<: *default
  database: db/prelaunchr_test.postgresql
  host: localhost
  
production:
  <<: *default
  database: db/prelaunchr_production.postgresql
  url:  <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV['DB_POOL'] || ENV['RAILS_MAX_THREADS'] || 5 %>
